import "./globals.css";
import Navbar from "./navBar/page";
import { CartProvider } from '../context/CartContext.jsx';
// import StyledComponentsRegistry from './registry';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        
          <CartProvider>
            <Navbar/>
            {children}
          </CartProvider>
       
      </body>
    </html>
  );
}
